---
#- name: Updating Yum repositories
#  when: "ansible_os_family == 'RedHat'"
#  yum:
#    update_cache=yes
#
#- name: Installing Yum Package {{ pkg }}
#  when: "ansible_os_family == 'RedHat'"
#  yum: 
#    name={{ pkg }}
#    state=latest

- name: Updating apt repositories from role
#  when: "ansible_os_family == 'Debian'"
  apt:
    update_cache=yes
    cache_valid_time=10000
- name: Installing Ubuntu Package {{ pkg }}
#  when: "ansible_os_family == 'Debian'"
  apt:
    name={{ pkg }}
    state=latest
#- fail: msg="x is not defined"
#  when: x is undefined
- name: Create list of servers from group
  template: src=testfile dest=/tmp
