---
- include_vars: "{{ ansible_os_family }}.yml"
- include: "{{ ansible_os_family }}.yml"

- name: Create list of servers from group
  template: src=inventory dest=/tmp/inventory.txt

- name: Create Config files 
  template: src=config dest=/tmp/config.txt

#- include: redhat.yml
#  when: ansible_os_family == 'RedHat'
#
#- include: ubuntu.yml
#  when: ansible_os_family == 'Debian'


#- name: Updating Yum repositories
#  when: "ansible_os_family == 'RedHat'"
#  yum:
#    update_cache=yes
#
#- name: Installing Yum Package {{ pkg }}
#  when: "ansible_os_family == 'RedHat'"
#  yum: 
#    name={{ pkg }}
#    state=latest
#
#- name: Updating apt repositories from role
#  when: "ansible_os_family == 'Debian'"
#  apt:
#    update_cache=yes
#    cache_valid_time=10000
#
#- name: Installing Ubuntu Package {{ pkg }}
#  when: "ansible_os_family == 'Debian'"
#  apt:
#    name={{ pkg }}
#    state=latest
