---
#- name: Removing Yum Package {{ pkg }}
##  apt: name={{ pkg }} state=absent autoremove=yes
#  when: "ansible_os_family == 'RedHat'"
#  yum:
#    name={{ pkg }}
#    state=absent

- name:  Removing Ubuntu  Package {{ pkg }}
#  apt: name={{ pkg }} state=absent autoremove=yes
  apt:
    name={{ pkg }}
    state=absent
    autoremove=yes
