---
- name: Removing Yum Package {{ pkg }}
#  apt: name={{ pkg }} state=absent autoremove=yes
  yum:
    name={{ pkg }}
    state=absent

#- name:  Removing Ubuntu  Package {{ pkg }}
##  apt: name={{ pkg }} state=absent autoremove=yes
#  when: "ansible_os_family == 'Debian'"
#  apt:
#    name={{ pkg }}
#    state=absent
#    autoremove=yes
